name: Build application
on: workflow_dispatch
jobs: 
  first-job:
    runs on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "build test successfull"
      - name: print good bye
        run: echo "build successfull" 
